### ISSUE TITLE
Copyrights, credits, legal mumbo jumbo in the page footer

### ISSUE THREAD

**Issue by dvndrsn** [linbug/planigale#16]
Proper credit should be displayed for each photo as well!

This will require changes in the species data fetched from EOL and stored in our pickle!

**Comment by linbug** [comment]
Also should include proper recognition and link to EOL on title page

**Comment by dvndrsn** [comment]
Also, should use proper jinja header and footer elements on all pages (code reuse = awesome)

**Comment by linbug** [comment]
oh, that jinja inheritence thingy?

**Comment by linbug** [comment]
need to include licence somewhere

**Comment by dvndrsn** [comment]
We can include the MIT Licence on the readme? Its permissive and fairly popular.

https://opensource.org/licenses/MIT
http://redmonk.com/sogrady/2014/11/14/open-source-licenses/
