### ISSUE TITLE
Terminal game is broken

### ISSUE THREAD

**Issue by linbug** [linbug/planigale#22]
Some terrible off-by-one error; also does not recognise when you have picked the right answer

**Comment by linbug** [comment]
Figured out this is due to `next_question` method no longer returning anything. Probably best to keep terminal game in a different file

**Comment by dvndrsn** [comment]
No worries, I'm going to break a lot of the functionality with my changes
too. :) It's a fact of software development that new features or bug fixes
can break existing functionality. We can just go back and make the
necessary changes when we're done.

**Comment by dvndrsn** [comment]
This is fixed as well w/ the improved answers page commit.
